services:
  - type: web
    name: pmlg-event-management
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: /up
    disk:
      name: sqlite-storage
      mountPath: /rails/storage
      sizeGB: 1
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: "development:test"
